[versions]
compose-bom = "2023.03.00"
activity = "1.7.2"

[libraries]
activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
bom = { group = "dev.chrisbanes.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { module = "androidx.compose.ui:ui" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
material3 = { module = "androidx.compose.material3:material3" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }

[bundles]
ui = ["ui", "ui-graphics", "ui-tooling-preview"]
